export const BOOKING_SERVICES_TYPES = require('./serviceTypes')
export const BOOKING_CONFIGS = require('./configs')
export const BOOKING_PRIVILEGES = require('./privileges')

export const BOOKING_USER_AUTH = 'BOOKING_USER_AUTH'
export const BOOKING_USER_PRIVILEGES = 'BOOKING_USER_PRIVILEGES'
export const BOOKING_USER_PRIVILEGE_AUTH = 'BOOKING_USER_PRIVILEGE_AUTH'
export const BOOKING_USER_CURRENT_STORE = 'BOOKING_USER_CURRENT_STORE'
export const BOOKING_USER_DISTRIBUTIONS = 'BOOKING_USER_DISTRIBUTIONS'
export const BOOKING_USER_STORES = 'BOOKING_USER_STORES'
export const BOOKING_USER_PIECES = 'BOOKING_USER_PIECES'
export const BOOKING_USER_PIECES_BY_DISTRIBUTE = 'BOOKING_USER_PIECES_BY_DISTRIBUTE'
export const BOOKING_USER_ORG_LIST = 'BOOKING_USER_ORG_LIST'
export const CURRENT_DISTRIBUTE = 'CURRENT_DISTRIBUTE'
